name: Build Windows App

on:
  push:
    branches: [ "main" ] # Löst den Build bei einem Push auf den main-Branch aus
  workflow_dispatch: # Ermöglicht manuelles Starten des Workflows in der GitHub UI

jobs:
  build-windows:
    # Dieser Job läuft auf einer von GitHub bereitgestellten Windows-Maschine
    runs-on: windows-latest

    steps:
      # 1. Code aus dem Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js einrichten (wird für den Neutralino-CLI benötigt)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Den Neutralinojs-CLI global installieren
      - name: Install Neutralinojs CLI
        run: npm install -g @neutralinojs/neu

      # 4. Framework-Binärdateien herunterladen/aktualisieren
      - name: Update Neutralinojs binaries
        run: neu update

      # 5. Die Anwendung für die Veröffentlichung bauen
      - name: Build the application
        run: neu build --release

      # 6. (DEBUG) Inhalt des Build-Ordners auflisten, um zu prüfen, ob die .exe existiert
      - name: List files in build directory
        run: ls -R dist
        shell: pwsh # Stellt sicher, dass der Befehl in PowerShell ausgeführt wird

      # 7. Die fertige ZIP-Datei als Artefakt hochladen
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: therapypay-app-windows
          path: dist/therapypay-app-release.zip
